name: homezapp

services:
  frontend:
    image: docker.io/jbollman/homez-app-repo:angular
    container_name: frontend-container
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: "docker.io/jbollman/homez-app-repo:api-sqlite"
    container_name: backend-container
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://db-container:3306/db_name
    networks:
      - app-network

  # database:
  #   image: "docker.io/jbollman/homez-app-repo:db"
  #   container_name: db-container
  #   networks:
  #     - app-network
  #   volumes:
  #     - db-data:/mydatabase
  #   #command: ["sqlite3", "/db/housing.db"]
  #   command: ["tail", "-f", "/dev/null"]

networks:
  app-network:

volumes:
  db-data:
