name: homezapp

services:
  frontend:
    image: docker.io/jbollman/homez-app-repo:angular
    container_name: frontend-container
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: "docker.io/jbollman/homez-app-repo:api-sqlite"
    container_name: backend-container
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=/app/housing.db
    networks:
      - app-network
    # volumes:
    #   - db-data:/app/housing.db

networks:
  app-network:

# volumes:
#   db-data:
